all: vcn_package
	javac Samples.java

vcn_package:
	javac mx/cimat/vcn/Box.java
	javac mx/cimat/vcn/Mesh.java
	javac mx/cimat/vcn/Model.java
	javac mx/cimat/vcn/GeometricBot.java
	javac mx/cimat/vcn/GeometricBotDraw.java